apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  triggers:
    - type: "GitHub"
      github:
        secret: "vote"
    - type: "ConfigChange"
  source:
    ref: docker
    git:
      uri: "https://github.com/ComputerScienceHouse/Vote.git"
  output:
    to:
      kind: ImageStreamTag
      name: vote:latest
  runPolicy: SerialLatestOnly
  strategy:
    dockerStrategy:
      env:
        - name: REACT_APP_SSO_CLIENT_ID
          value: vote
        - name: REACT_APP_SSO_AUTHORITY
          value: https://sso.csh.rit.edu/auth/realms/csh
        - name: REACT_APP_BASE_API_URL
          value: https://vote.csh.rit.edu
    type: Docker
  # Lookup local images
  lookupPolicy:
    local: true
  status:
    tags:
    - items:
      tag: latest
